#!/bin/bash
#
# Author: Jeffrey Cutter
# Licence: GPL v3
#
# Note: This program can enable you to do things faster, including mistakes, use at your own risk.
#

NAME=$(basename $0)
DIR=$(dirname $0)

function usage {
  echo
  case $NAME in
    "cfssh") echo "USAGE: $NAME group command args" ;;
    "cfscp") echo "USAGE: $NAME group local_file remote_dest_dir" ;;
    "cfcollect") echo "USAGE: $NAME group remote_file local_dest_dir" ;;
  esac
  echo
  echo "	Available groups:"
  for i in `ls $DIR/cfhosts.*`
  do
    j=$(basename $i | sed 's/^cfhosts\.//')
    echo "	$j"
  done
  echo
  echo "-h | --help for this usage statement"
  echo
  exit 1
}

if [[ $1 == "-h" || $1 == "--help" || $# -eq 0 ]]
then
  usage
fi

if [ "$NAME" == "cfssh" ]
then
  if [ $# -lt 2 ]
  then
    echo
    echo "Not enough arguments!"
    usage
  fi
else
  if [ $# -ne 3 ]
  then
    echo
    echo "Wrong number of arguments!"
    usage
  fi
fi

group=$1
shift

FILE="$DIR/cfhosts.$group"

if [ ! -r "$FILE" ]
then
  echo
  echo "Group $group not available!"
  usage
fi

echo
for i in `cat $FILE | grep -v "^#"`
do
  echo "*** $i ***"
  case $NAME in
    "cfssh") ssh root@$i $* ;;
    "cfscp") scp $1 root@$i:$2 ;;
    "cfcollect") scp root@$i:$1 $2/$(basename $1)-$i ;;
  esac
  echo
done
