#!/bin/bash
#
# Author: Jeffrey Cutter
# License: GPL v3
#
# Note: This program can enable you to do things faster, including mistakes, use at your own risk.
#

NAME=$(basename $0)
DIR=$(dirname $0)
cfhosts_cmd="$DIR/cfhosts.rb"
cfhosts_file="$DIR/cfhosts"

groups=$($cfhosts_cmd $cfhosts_file list_groups)

function usage {
  echo
  case $NAME in
    "cfssh") echo "USAGE: $NAME group command args" ;;
    "cfscp") echo "USAGE: $NAME group local_file remote_dest_dir" ;;
    "cfcollect") echo "USAGE: $NAME group remote_file local_dest_dir" ;;
    "cfgrep") echo "USAGE: $NAME [-i] group pattern log_file [count]" ;;
  esac
  echo
  echo "	Available groups:"
  for i in $groups
  do
    echo "	$i"
  done
  echo
  echo "To see matching hosts for a given group, use:"
  echo
  echo "$NAME <group> list"
  echo
  echo "-h | --help for this usage statement."
  echo
  exit 1
}

GREP="egrep"
if [ "$NAME" == 'cfgrep' ]
then
  if [ "$1" == '-i' ]
  then
    GREP="$GREP -i"
    shift
  fi
fi

if [[ $1 == "-h" || $1 == "--help" || $# -eq 0 ]]
then
  usage
fi

if [[ "$NAME" == "cfssh" || "$2" == "list" ]]
then
  if [ $# -lt 2 ]
  then
    echo
    echo "Not enough arguments!"
    usage
  fi
elif [ "$NAME" == "cfgrep" ]
then
  if [[ $# -ne 3 && $# -ne 4 ]]
  then
    echo
    echo "Wrong number of arguments!"
    usage
  fi
else
  if [ $# -ne 3 ]
  then
    echo
    echo "Wrong number of arguments!"
    usage
  fi
fi

group=$1
shift

if [ ! -r "$cfhosts_file" ]
then
  echo
  echo "$cfhosts_file not available!"
  usage
fi

if [ ! -x "$cfhosts_cmd" ]
then
  echo
  echo "$cfhosts_file not executable!"
  usage
fi

group_good=false

for i in $groups
do
  if [ "$i" == "$group" ]
  then
    group_good=true
  fi
done

if [ "$group_good" != "true" ]
then
  echo
  echo "Group $group not found in $cfhosts_file"
  usage
fi

echo

SERVERS=$($cfhosts_cmd $cfhosts_file list_servers $group)

if [ "$1" == "list" ]
then
  echo "Matching servers:"
  for i in $SERVERS
  do
    echo $i
  done
  exit
fi

TAIL="tail -5"
if [ "$NAME" == 'cfgrep' ]
then
  PATTERN="$1"
  LOG=$2
  if [ "$(echo $LOG | cut -c1)" != "/" ]
  then
    LOG="/var/www/miq/vmdb/log/$(echo $LOG | sed 's/\.log$//').log"
  fi
  if [ -n "$3" ]
  then
    TAIL="tail -$3"
  fi
fi

ARGS=$*
ARGS=$(echo $ARGS | sed 's/*/\\*/g')

for i in $SERVERS
do
  echo "*** $i ***"
  case $NAME in
    "cfssh") ssh root@$i $ARGS ;;
    "cfscp") scp $1 root@$i:$2 ;;
    "cfcollect") scp root@$i:$1 $2/$(basename $1)-$i ;;
    "cfgrep") ssh root@$i $GREP "$PATTERN" $LOG \| $TAIL
  esac
  echo
done
