#!/bin/bash

DIR=$(dirname $(realpath $0))
DEST=$(dirname $DIR)
cat $DIR/HEAD.md > $DEST/README.md

commands="miqssh miqscp miqcollect miqgrep miqtail"

for i in $commands
do
  echo "## $i"
  echo '```'
  $DEST/$i -h
  echo '```'
done >> $DEST/README.md

cat $DIR/FOOT.md >> $DEST/README.md
