#!/bin/bash

commands="cfssh cfscp cfcollect cfgrep cfgrep-collate cfgrep-request cftail cftail-request"

for i in $commands
do
  echo "##$i"
  echo '```'
  ~/git/cf_shortcuts/cfssh/$i -h
  echo '```'
done
