#!/bin/bash

cat ~/git/cf_shortcuts/cfssh/doc-tools/HEAD.md > ~/git/cf_shortcuts/cfssh/README.md

commands="cfssh cfscp cfcollect cfgrep cftail"

for i in $commands
do
  echo "## $i"
  echo '```'
  ~/git/cf_shortcuts/cfssh/$i -h
  echo '```'
done >> ~/git/cf_shortcuts/cfssh/README.md

cat ~/git/cf_shortcuts/cfssh/doc-tools/FOOT.md >> ~/git/cf_shortcuts/cfssh/README.md
