#!/bin/bash

for i in `cfssh -q -g all list`
do
  echo -n "$i: "
  RESULT=$(curl -m 10 -k https://$i/ping 2> /dev/null)
  if [ "$RESULT" != 'pong'  ]
  then
    echo "ERROR"
  else
    echo "OK"
  fi
done

