#!/bin/bash

FILES="GUID REGION certs/v2_key config/database.yml"
DIR=$1

if [ -z "$DIR" ]
then
  echo
  echo "USAGE: $(basename $0) dest_dir"
  echo
  exit 1
fi

if [ ! -d "$DIR" ]
then
  echo "echo $DIR does not exist."
  exit 1
fi

for FILE in $FILES
do
  miqcollect /var/www/miq/vmdb/$FILE .
done

